"""Saturated Groebner tests over K = Q(z) for local weighted matching potentials.

Given a digraph D on {0..n-1}, a graph U on D's vertices plus nf frozen environment vertices
{n..n+nf-1}, and optional self-energies eta (elements of Q(z)), the unknowns are the vertex
weights a_0, ..., a_{n+nf-1}.  A (frozen) potential is a solution of

    mu_a(U[(W - v) + F]) - R(W, v) * mu_a(U[W + F]) = 0      for every reachable position (W, v) of D,
    mu_a(U[W + F]) != 0                                       for every reachable unvisited set W,

where F is the environment and R(W, v) the exact root resolvent (with self-energies eta).
Let I be the ideal of K[a] generated by the equations and J its saturation by the product f of
the nonvanishing polynomials, J = I : f^infinity.  By Hilbert's Nullstellensatz over K,

    J = (1)   <=>   the system has no solution with weights in the algebraic closure of K.

So `decide(...) == False` proves that no potential exists even with algebraic-function weights,
and `decide(...) == True` shows that a solution exists over the algebraic closure (it need not
be rational or real; see Section 10 of the paper, Lemma 10.1).

Backends
  'singular'  passagemath's Singular interface (fast; module sage.all__sagemath_singular)
  'sympy'     pure Python: Rabinowitsch trick 1 - t*f and a Buchberger basis over QQ(z)
  'auto'      'singular' when importable, else 'sympy'
"""
from __future__ import annotations

import itertools
from typing import Dict, FrozenSet, Iterable, List, Optional, Sequence, Tuple

from .dvg import Digraph, QZ

Edge = Tuple[int, int]

try:  # optional fast backend
    from sage.all__sagemath_singular import PolynomialRing as _SPolyRing, QQ as _SQQ, \
        FractionField as _SFrac  # type: ignore
    _HAVE_SINGULAR = True
except Exception:  # pragma: no cover - depends on the environment
    _HAVE_SINGULAR = False


def have_singular() -> bool:
    return _HAVE_SINGULAR


# ---------------------------------------------------------------------------- the system
def _mu(S: FrozenSet[int], adj: Dict[int, List[int]], a, one, memo):
    if S in memo:
        return memo[S]
    if not S:
        return one
    v = min(S)
    rest = S - {v}
    val = a[v] * _mu(rest, adj, a, one, memo)
    for w in adj.get(v, ()):
        if w in rest:
            val = val - _mu(rest - {w}, adj, a, one, memo)
    memo[S] = val
    return val


def potential_system(D: Digraph, U: Iterable[Edge], nf: int = 0,
                     eta: Optional[Dict[int, object]] = None):
    """Return (positions, resolvent values, adjacency of U, environment set).  Resolvent values
    are elements of Q(z) (sympy FracElement)."""
    N = D.n + nf
    adj: Dict[int, List[int]] = {}
    for (i, j) in U:
        if not (0 <= i < N and 0 <= j < N) or i == j:
            raise ValueError('bad edge %r' % ((i, j),))
        adj.setdefault(i, []).append(j)
        adj.setdefault(j, []).append(i)
    F = frozenset(range(D.n, N))
    R = D.resolvent_function(eta=eta)
    pos = sorted(D.reachable_positions(), key=lambda p: (-len(p[0]), sorted(p[0]), p[1]))
    vals = [R(W, v) for (W, v) in pos]
    return pos, vals, adj, F


# ---------------------------------------------------------------------------- sympy backend
def _decide_sympy(D, U, nf, eta) -> bool:
    import sympy as sp
    from sympy.polys.rings import ring
    from sympy.polys.orderings import grevlex
    from sympy.polys.groebnertools import groebner

    pos, vals, adj, F = potential_system(D, U, nf, eta)
    N = D.n + nf
    zs = sp.Symbol('z')
    dom = sp.QQ.frac_field(zs)
    names = ['a%d' % i for i in range(N)] + ['t_sat']
    Rng, *gens = ring(','.join(names), dom, grevlex)
    a = {i: gens[i] for i in range(N)}
    t = gens[N]
    one = Rng(1)
    memo: Dict[FrozenSet[int], object] = {}
    eqs = []
    Ws = set()
    for (W, v), r in zip(pos, vals):
        rc = dom.from_sympy(r.as_expr())
        num = _mu((W - {v}) | F, adj, a, one, memo)
        den = _mu(W | F, adj, a, one, memo)
        e = num - den * rc
        if e != 0:
            eqs.append(e)
        Ws.add(W)
    prod = one
    for W in Ws:
        f = _mu(W | F, adj, a, one, memo)
        if f == 0:
            return False
        prod = prod * f
    if not eqs:
        return True
    G = groebner(eqs + [one - t * prod], Rng)
    return not (len(G) == 1 and G[0].is_ground and G[0] != 0)


# ---------------------------------------------------------------------------- Singular backend
def _to_sage(fr, Kz, z):
    """Convert a sympy FracElement of Q(z) to an element of Sage's Frac(QQ[z])."""
    def poly(p):
        s = Kz(0)
        for (e,), c in p.terms():
            s += Kz(_SQQ(int(c.numerator)) / _SQQ(int(c.denominator))) * z ** e
        return s
    return poly(fr.numer) / poly(fr.denom)


def _decide_singular(D, U, nf, eta) -> bool:
    pos, vals, adj, F = potential_system(D, U, nf, eta)
    N = D.n + nf
    Rz = _SPolyRing(_SQQ, 'z')
    z = Rz.gen()
    Kz = _SFrac(Rz)
    A = _SPolyRing(Kz, ['a%d' % i for i in range(N)], order='degrevlex')
    al = A.gens()
    a = {i: al[i] for i in range(N)}
    one = A(1)
    memo: Dict[FrozenSet[int], object] = {}
    eqs = []
    Ws = set()
    for (W, v), r in zip(pos, vals):
        rc = A(_to_sage(r, Kz, z))
        e = _mu((W - {v}) | F, adj, a, one, memo) - rc * _mu(W | F, adj, a, one, memo)
        if e != 0:
            eqs.append(e)
        Ws.add(W)
    nonzero = [_mu(W | F, adj, a, one, memo) for W in Ws]
    if any(f == 0 for f in nonzero):
        return False
    if not eqs:
        return True
    J = A.ideal(eqs)
    for f in nonzero:
        if f.is_constant():
            continue
        J = J.saturation(A.ideal([f]))[0]
        if J.is_one():
            return False
    return not J.is_one()


# ---------------------------------------------------------------------------- public API
def decide(D: Digraph, U: Iterable[Edge], nf: int = 0, eta: Optional[Dict[int, object]] = None,
           backend: str = 'auto') -> bool:
    """True iff (D, U) admits a (frozen) potential with weights in the algebraic closure of Q(z)."""
    U = [tuple(e) for e in U]
    if backend == 'auto':
        backend = 'singular' if _HAVE_SINGULAR else 'sympy'
    if backend == 'singular':
        if not _HAVE_SINGULAR:
            raise RuntimeError('Singular backend unavailable; install passagemath-singular')
        return _decide_singular(D, U, nf, eta)
    if backend == 'sympy':
        return _decide_sympy(D, U, nf, eta)
    raise ValueError('unknown backend %r' % backend)


def all_graphs(N: int):
    """All graphs on {0..N-1} (as edge lists), 2^(N choose 2) of them."""
    pairs = [(i, j) for i in range(N) for j in range(i + 1, N)]
    for k in range(len(pairs) + 1):
        for c in itertools.combinations(pairs, k):
            yield list(c)


def search(D: Digraph, nf: int = 0, eta=None, graphs: Optional[Iterable[Sequence[Edge]]] = None,
           backend: str = 'auto') -> List[List[Edge]]:
    """All graphs U (from `graphs`, default: every graph on n + nf vertices) for which a (frozen)
    potential exists over the algebraic closure of Q(z)."""
    found = []
    for U in (graphs if graphs is not None else all_graphs(D.n + nf)):
        if decide(D, U, nf, eta, backend):
            found.append(list(U))
    return found
